### ISSUE TITLE
请问一下，训练和测试数据去哪里下载？

### ISSUE THREAD

**Issue by muguet9764** [rxy007/cnn-lstm-crf#1]
Using TensorFlow backend.
start ######load train data #####
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    train_data, train_char_set = load_data(train_file)
  File "/home/jupyter/workspace/syj/CLC/data.py", line 77, in load_data
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/train_data'

**Comment by rxy007** [comment]
我们使用的私有数据集，不过你可以找公开数据集测试



***@***.***
 
发件人： muguet9764
发送时间： 2023-06-17 16:03
收件人： rxy007/cnn-lstm-crf
抄送： Subscribed
主题： [rxy007/cnn-lstm-crf] 请问一下，训练和测试数据去哪里下载？ (Issue #1)
